source: .
destination: ./_site
collections_dir: .
plugins_dir: ./build/_plugins # takes an array of strings and loads plugins in that order
layouts_dir: ./build/_layouts
data_dir: ./build/_data
includes_dir: ./build/_includes
sass:
  sass_dir: ./build/_sass
collections:
  posts:
    output: true

# Handling Reading
safe: false
include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
  ]
keep_files: [".git", ".svn"]
encoding: "utf-8"
